name: Create .exe from Python code

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Semantic versioning
      id: versioning
      uses: PaulHatch/semantic-version@v4.0.2
      with:
        branch: main
        tag_prefix: "v"
        major_pattern: "BREAKING CHANGE:"
        minor_pattern: "feat:"
        format: "v${major}.${minor}.${patch}-prerelease${increment}"
    - name: Extract version from commit message
      run: |
        $COMMIT_MESSAGE = "${{ github.event.head_commit.message }}"
        Write-Output $COMMIT_MESSAGE | Select-String -AllMatches -Pattern "v[0-9.]+"
        $VERSION = Write-Output $COMMIT_MESSAGE | Select-String -AllMatches -Pattern "v[0-9.]+" | Out-File -FilePath $env:GITHUB_ENV
        echo ("VERSION=" + $env:GITHUB_REF.replace('refs/heads/', '')) >> $env:GITHUB_ENV
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        draft: false
        prerelease: false
